name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"   # JST 03:00
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: profile-3d
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Pull (rebase) latest main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git pull --rebase origin main

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: shin1300

      - name: Commit & Push
        run: |
          git add -A .
          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi
          git commit -m "generated 3d profile contributions"
          git push origin HEAD:main
