name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"  
  workflow_dispatch:

permissions:
  contents: write         
  pull-requests: write    

concurrency:
  group: profile-3d
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main                

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: shin1300

      - name: Check diff
        id: diff
        run: |
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "generated 3d profile contributions"
          title: "chore(profile-3d): update generated SVGs"
          body: |
            Automated update of profile 3D contribution SVGs.
            - Trigger: ${{ github.event_name }}
            - Commit: ${{ github.sha }}
          branch: chore/profile-3d/update-${{ github.run_id }}
          base: main
          labels: |
            automated
            profile-3d
          delete-branch: true   
