name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"  
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: profile-3d
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0       
          ref: main            

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: shin1300

      - name: Commit & Rebase & Push (with retry)
        run: |
          set -euo pipefail
          set -x

          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -A .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "generated 3d profile contributions"

          BRANCH="main"

          for i in 1 2 3; do
            git fetch origin "$BRANCH"
            if git rebase "origin/$BRANCH"; then
              if git push origin "HEAD:$BRANCH"; then
                echo "Pushed successfully."
                exit 0
              fi
            else
              echo "Rebase failed. Aborting…"
              git rebase --abort || true
            fi
            echo "Retry $i failed; sleeping and retrying…"
            sleep $((i * 5))
          done

          echo "Failed to push after retries."
          exit 1
