name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"   # JST 03:00
  workflow_dispatch:

# ワークフローにも書き込み権限を明示
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: shin1300   # あなたのユーザー名

      # ← ココが重要：生成物をコミット＆プッシュ
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A .
          if git commit -m "generated 3d profile contributions"; then
            git push
          fi
